framework:
    cache:
        app: app.cache.pool
        system: cache.adapter.array
        default_redis_provider: '%env(REDIS_URL)%'
        pools:
            app.cache.pool:
                adapters:
                    - cache.array.pool
                    - app.cache.redis.pool

            app.cache.redis.pool:
                adapter: app.cache.adapter.redis
                provider: cache.provider.redis.pool
                default_lifetime: '%default_array_cache_ttl%'

            cache.array.pool:
                adapter: app.cache.adapter.array

            # used directly from services.yaml
            http.cache.redis.pool:
                adapter: http.cache.adapter.redis
                provider: cache.provider.redis.pool
                default_lifetime: '%default_http_cache_ttl%'
parameters:
    default_array_cache_ttl: 30
    default_http_cache_ttl: 1200
    redis.dsn: '%env(REDIS_URL)%'
    redis.namespace: '%env(REDIS_NAMESPACE_PREFIX)%'

services:
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    cache.provider.redis.pool:
        class: Redis
        public: true
        factory: ['Symfony\Component\Cache\Adapter\RedisAdapter', 'createConnection']
        arguments:
            $dsn: '%redis.dsn%'

    app.cache.adapter.redis:
        parent: cache.adapter.redis
        arguments:
            $namespace: '%redis.namespace%'

    http.cache.adapter.redis:
        parent: cache.adapter.redis
        arguments:
            $namespace: '%redis.namespace%_http_cache'

    app.cache.factory.array:
        class: App\Infrastructure\Cache\Array\ArrayAdapterFactory
        arguments:
            $maxItems: 100000
            $maxLifetime: '%default_array_cache_ttl%'

    app.cache.adapter.array:
        class: Symfony\Component\Cache\Adapter\ArrayAdapter
        factory: [ '@app.cache.factory.array', 'create' ]
        arguments: [ '%redis.namespace%' ]