monolog:
    channels: [ 'app', 'errors' ]
    handlers:
        app:
            type: stream
            path: php://stderr
            level: debug
            channels: [ '!event', '!doctrine', '!request', '!security', '!messenger' ]
