version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: ./.ops/docker/php/Dockerfile
    container_name: symfony_app
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "false"
      REDIS_URL: "redis://redis:6379"
      REDIS_NAMESPACE_PREFIX: "example_http_cache_app"
    volumes:
      - .:/var/www/html
    depends_on:
      - redis

  web:
    image: nginx:alpine
    container_name: symfony_nginx
    volumes:
      - .:/var/www/html
      - ./.ops/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"
    depends_on:
      - app

  redis:
    image: redis:6.2
    container_name: symfony_redis
    ports:
      - "6379:6379"
